### ISSUE TITLE
Missing item segment

### ISSUE THREAD

**Issue by SinisaStrbac** [php-edifact/edifact-generator#11]
PIA ( To specify additional or substitutional item identification codes ) segment is missing in Order Item . Possible to add it please ?

**Comment by viezel** [comment]
You mean this? 
https://www.gs1si.org/Standardi/EANCOM-2012/ean02s3/part2/orders/0548.htm

**Comment by SinisaStrbac** [comment]
Tes,  exactly this.  Thank you

**Comment by viezel** [comment]
Fixed in https://github.com/php-edifact/edifact-generator/releases/tag/1.0.4

**Comment by viezel** [comment]
```
$item = new Orders\Item();
$item->setAdditionalProductId('1', '313322', 'SA');
```

**Comment by SinisaStrbac** [comment]
Thank you for your help
