### ISSUE TITLE
CNT segment error

### ISSUE THREAD

**Issue by SinisaStrbac** [php-edifact/edifact-generator#13]
Hello there is an error in item count section, in this part you can see **CNT+2+2** and it should be **CNT+2:2**
...
PIA+G144621+5:IN'
QTY+12:7:PCE'
PRI+AAA:12.96:::1:PCE'
LIN+2++3573678678200:EN'
PIA+G144712+5:IN'
QTY+12:7:PCE'
PRI+AAA:6.90:::1:PCE'
UNS+S'
**CNT+2+2'**
...

Thank you

**Comment by sabas** [comment]
cc @viezel

**Comment by viezel** [comment]
@SinisaStrbac thanks for the two issues you spotted 👍. Those are fixed and I bumped the composer version to `1.0.6`
