### ISSUE TITLE
Item quantity qualifier

### ISSUE THREAD

**Issue by SinisaStrbac** [php-edifact/edifact-generator#14]
Hello,
In Trait "Item", function setQuantity should have $quantifier parameter.
For example when i make "ORDERS" and $item->setQuantity, item qualifier must be 21 ( "Orderded quantity" qualifier ) not 12 ( "Despatch quantity" qualifier )

** /traits/Item.php l.173:**
$this->quantity = [
            'QTY',
            [
                **'12'**,
                (string)$quantity,
                $unit,
            ],
        ];

**Comment by viezel** [comment]
thanks :)
