### ISSUE TITLE
[Help Wanted] Formatting & Working with output

### ISSUE THREAD

**Issue by JoshStaff** [php-edifact/edifact-generator#20]
Hey.

First things first, thank you for the hard work that has gone into this package. I am currently working with a fork & am implementing a QUOTE implementation for EDIFACT.

I've never worked with this standard / file so I'm by no means an expert, I am struggling to conform to the output provided by our example files however.

As an example, I'm currently adding a GIR segment in my fork & have noticed my example segments look as follow:

```
GIR+001+D:LLO+DVDN:LSQ+STOCK_AV:LFN+10.21:LCV
GIR+002+P:LLO+DVDN:LSQ+STOCK_AV:LFN+10.21:LCV
GIR+003+CW:LLO+DVDN:LSQ+STOCK_AV:LFN+10.21:LCV
```

When I generate my test data using a similar approach to the other examples within the project, I get:

```
GIR+1:D:LLO
```

Which I assume is to be expected, I am however wondering how to specify that the `$sepData` character should be used? Am I missing something? My DTM etc are all formatting correctly.

Happy to PR this back once the quote functionality is working if it would be of value. Any help regarding the internals would be appreciated. Thanks again!

**Comment by sabas** [comment]
Did you solve it?
If needed you can also write me an email with the sample!
Ciao,
Stefano
