### ISSUE TITLE
packagist - source reference

### ISSUE THREAD

**Issue by davidvandertuijn** [php-edifact/edifact-generator#9]
I having problems updating this library to the latest changes using composer update.

If i look at packagist the latest source reference is '7bb1aeea77338e5090f65ced3ca425c667ffa42d'
https://packagist.org/packages/php-edifact/edifact-generator

This is a reference to an old commit:
https://github.com/php-edifact/edifact-generator/commit/7bb1aeea77338e5090f65ced3ca425c667ffa42d

Why is this source reference not updated ?

**Comment by sabas** [comment]
Perhaps the webhook was gone, I forced the update from packagist, and now I see the webhook as well.
